# Settings for the app
app:
  # HTML Title
  title: Participatory Budgeting NYC - District 39
  # Header name
  name: Participatory Budgeting NYC - District 39
  # Meta description that will show up in Google search results
  meta_description: _(Participatory Budgeting for NYC)

# Settings for map and layer configs
map:
  geolocation_enabled: true
  geolocation_onload: false
  options:
    center:
      lat: 40.673673020430236
      lng:  -73.99506568908691
    zoom: 15
    minZoom: 13
    maxZoom: 17
  base_layer:
    url: http://{s}.tiles.mapbox.com/v3/openplans.map-dmar86ym/{z}/{x}/{y}.png
    attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>'
  layers: []

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  culture:
    default: blue
    focused: red
    label: _(Culture & Community Facilities)
  education:
    default: blue
    focused: red
    label: _(Schools & Education)
  environment:
    default: blue
    focused: red
    label: _(Environment)
  housing:
    default: blue
    focused: red
    label: _(Housing)
  parks:
    default: blue
    focused: red  
    label: _(Parks & Recreation)
  health:
    default: blue
    focused: red
    label: _(Public Health)
  safety:
    default: blue
    focused: red
    label: _(Public Safety)
  seniors:
    default: blue
    focused: red
    label: _(Seniors)
  streets:
    default: blue
    focused: red
    label: _(Streets & Sidewalks)
  transit:
    default: blue
    focused: red
    label: _(Transit)
  youth:
    default: blue
    focused: red
    label: _(Youth)

# Defines place icons. See http://leaflet.cloudmade.com/reference.html#icon
# for documention of each property. Any omitted property will be undefined.
place_type_icons:
  blue:
    iconUrl: /static/css/images/feature-point.png
    iconSize:
      width: 17
      height: 18
    iconAnchor:
      x: 9
      y: 9
  red:
    iconUrl: /static/css/images/marker-focused.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41


activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true
  # How often to refresh the activity list, in milliseconds.
  interval: 30000

place:
  adding_supported: true
  add_button_label: _(Add an idea)
  action_text: _(added)
  title: _(Describe your idea)
  action_text: _(created)
  anonymous_name: _(Someone)
  submit_button_label: _(Share my idea)
  items:
    - prompt: _(Your idea)
      type: text
      name: name
      attrs:
        - key: placeholder
          value: _(Brief description)
        - key: size
          value: 30
    - prompt: _(Why do you want this?)
      type: textarea
      name: description
      attrs:
        - key: placeholder
          value: _(Description...)
    - prompt: _(Pick a category for your idea)
      type: select
      options:
        - label: _(Please choose...)
          value: 
        - label: _(Culture & Community Facilities)
          value: culture
        - label: _(Schools & Education)
          value: education
        - label: _(Environment)
          value: environment
        - label: _(Housing)
          value: housing
        - label: _(Parks & Recreation)
          value: parks
        - label: _(Public Health)
          value: health
        - label: _(Public Safety)
          value: safety
        - label: _(Seniors)
          value: seniors
        - label: _(Streets & Sidewalks)
          value: streets
        - label: _(Transit)
          value: transit   
        - label: _(Youth)
          value: youth
      name: location_type
    - prompt: _(Image)
      inputfile_label: _(Add an image)
      type: file
      name: my_image
      attrs:
        - key: accept
          value: image/*
    - prompt: _(Your name, will be shown on the map)
      type: text
      name: submitter_name
      optional: false
      attrs:
        - key: placeholder
          value: _(Name)
        - key: size
          value: 30
    - prompt: _(Your email, will not be shown)
      type: text
      name: private-email
      attrs:
        - key: placeholder
          value: _(Email)
        - key: size
          value: 30
    - prompt: _(Your zip code, will not be shown)
      type: text
      name: private-zip
      attrs:
        - key: placeholder
          value: _(Zip)
        - key: size
          value: 30
survey:
  submission_type: comments

  # Response config
  show_responses: true
  response_name: _(comment)
  response_plural_name: _(comments)
  action_text: _(commented on)
  anonymous_name: _(Someone)

  # Survey form config
  title: _(Leave a Comment)
  form_link_text: _(Leave a Comment)
  submit_btn_text: _(Comment)
  items:
    - prompt: _(Comment)
      label: _(Comment)
      type: textarea
      name: comment
    - prompt: _(Your Name)
      type: text
      name: submitter_name

support:
  submission_type: support
  submit_btn_text: _(Support This!)
  action_text: supported
  anonymous_name: _(Someone)
